services:
  php:
    build: .
    working_dir: /app
    volumes:
      - ./:/app
      - composer_cache:/root/.composer/cache
    tty: true
    stdin_open: true
    command: tail -f /dev/null

volumes:
  composer_cache:
