version: "3.9"

services:
  php:
    build: .
    working_dir: /app
    volumes:
      - ./:/app
      - composer_cache:/root/.composer/cache
    command: bash -lc "php -v && bash"

volumes:
  composer_cache:
